fix bug when model is mono
AssertionError: stereo needs to be set to True if passing in audio signal that is stereo (channel dimension of 2). also need to be False if mono (channel dimension of 1)
ValueError: too many values to unpack (expected 3)
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now